name: Deploy to S3

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload static site to S3
        run: |
          aws s3 cp index.html s3://${{ secrets.S3_BUCKET }}/index.html --acl public-read
          aws s3 cp script.js s3://${{ secrets.S3_BUCKET }}/script.js --acl public-read
          aws s3 cp styles.css s3://${{ secrets.S3_BUCKET }}/styles.css --acl public-read
          aws s3 cp images/ s3://${{ secrets.S3_BUCKET }}/images/ --recursive --acl public-read
